### ISSUE TITLE
Spawner not Spawning Custom Mob

### ISSUE THREAD

**Issue by Thewhitegui** [goncalomb/NBTEditor#35] opened 2019-03-30 00:35 UTC
The spawner wont spawn a mob that was made with Bos but works perfectly for a normal Entity when put into the same spawner.

**Comment by Thewhitegui** [comment] 2019-03-30 00:37
Just flew to Map Spawn and they were all spawning at Spawn. So they are spawning but spawning in the wrong area

**Comment by Combustible** [comment] 2020-01-21 00:54
This happens when you use `/bos getempty` to pick up a mob and put it in a BoS, then you put that mob into a spawner with `/nbts additem`. 

The problem is that the empty book picks up all mob NBT data, including position. So when the mob spawns, it will spawn with the same position as the picked-up mob, even though your spawner is placed elsewhere. 

To fix this, you need to run `/bos clearvar Position` before adding it to a spawner. You may also want to clear Velocity and Rotation, depending on what you're doing. 

This is not an NBTEditor bug. @goncalomb should close this.

**Closed as completed** 2020-04-18 15:55 UTC
