### ISSUE TITLE
Bug in setting lore

### ISSUE THREAD

**Issue by enterih** [goncalomb/NBTEditor#41] opened 2019-11-11 15:56 UTC
/nbtitem lore add 
does only accept numbers on my side.

**Comment by Combustible** [comment] 2020-01-21 00:56
You need to use `/nbti **var** lore add Text`

**Comment by Chaoswizard98** [comment] 2020-02-14 00:53
I can confirm this bug still exists. Lore text changed in 1.14 to use json format.
/nbtitem var lore add Text Does nothing.
/nbtitem var lore add number Adds a line of lore that is set to whatever number you gave it
I also converted the following items (post command) to command block and pasted the nbt data below.

Examples:
/nbti var lore add 1
{display:{Lore:['{"text":"1"}']}}
This correctly shows a purple lore text of "1."

/nbti var lore add h
in command block: {display:{Lore:["h"]}}
This shows nothing.

**Comment by Combustible** [comment] 2020-03-18 04:07
This will be fixed when #47 lands for 1.15. In the meantime, you can work around this by simply putting quotes around your lore text entries like: 
```
/nbti var lore add "1"
```
Since a quoted string is valid JSON

**Comment by goncalomb** [comment] 2020-04-18 15:21
Yes, fixed on #47 and merged.

The latest builds on the new Jenkins server (https://jenkins.goncalomb.com/job/NBTEditor/) are compatible with 1.14 and 1.15, more features like missing variables will be added later.

**Closed as completed** 2020-04-18 15:21 UTC
